### ISSUE TITLE
import `@celo/react-celo/lib/styles.css` causes interface background to be incomplete

### ISSUE THREAD

**Issue by kyscott18** [celo-org/react-celo#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Background gets cut of at 100 view height. This was not the case when I was still using use-contractkit latest version.

### Steps to reproduce

1. Add a background to a site
2. add the newest react-celo package

### Expected behavior

n/a

### Screenshot

<img width="948" alt="Screen Shot 2022-06-13 at 5 42 35 PM" src="https://user-images.githubusercontent.com/43524469/173450482-61111bcb-285f-458b-9fb9-1298bc22447e.png">

### Where is the problem happening?

Desktop

### Environment

brave

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.0.0

**Comment by aaronmgdr** [comment]
@kyscott18 Do you have a branch up which adds the gradient? 

I have a fork of mobius thats fairly up to date with react-celo running and so far the existing gradient seems to go all the way down. 

I do see a few things in our code changes that might have caused this but want to be sure

**Comment by kyscott18** [comment]
@aaronmgdr just added you to our private repo https://github.com/mobiusAMM/mobius-interface2 .

**Comment by aaronmgdr** [comment]
My experiments show this is caused by 

```
html {
  height: -webkit-fill-available
}

```

which was added for a fix on a bug on mobile. 

we should investigate other ways and / or using media queries. 




*Workaround until next release for those effected. set html height to 'initial' or another property.*


cc @nicolasbrugneaux

**Comment by aaronmgdr** [comment]
just released beta for 4.0.1 which fixes this https://www.npmjs.com/package/@celo/react-celo/v/4.0.1-beta.1 


see this PR for more details https://github.com/celo-org/react-celo/pull/277

**Comment by obernardovieira** [comment]
It's also happening to me with very basic html elements. I have a example react app used to test while building a lib and it gets very different.

(I might be doing something wrong though, sorry if that's the case)
(I'm using the beta.1)
I'll leave here two examples, before and after, and the PR
https://github.com/impactMarket/utils/pull/139
Before
![image](https://user-images.githubusercontent.com/19441097/175645741-8f886bbd-588a-42d7-b96a-07d442dd73c3.png)
After
![image](https://user-images.githubusercontent.com/19441097/175645865-a183b8b4-7a4d-444e-8f4b-555911642b26.png)

**Comment by aaronmgdr** [comment]
@obernardovieira 

Ive released another beta for 4.0.1 https://www.npmjs.com/package/@celo/react-celo/v/4.0.1-beta.2

the css import that was bringing in global styles is gone

**Comment by obernardovieira** [comment]
fixed 🎉  thank you 😊
