### ISSUE TITLE
When metamask is locked, should not open the popup asking me to unlock

### ISSUE THREAD

**Issue by obernardovieira** [celo-org/react-celo#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If I've connected metamask before and I have it locked, when entering the website it asks me to unlock.

### Steps to reproduce

1. go to https://react-celo.vercel.app/
2. connect with metamask
3. lock metamask
4. refresh the page

### Expected behavior

After step 4. (refreshing the page), the user should not be asked to unlock metamask.

### Where is the problem happening?

Desktop

### Environment

browser: Brave
os: macOS 12.4

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.0.1-dev

### What wallet were you using?

metamask

**Comment by aaronmgdr** [comment]
I might be misunderstanding this but I think 4.1 no longer does this behavior.

**Comment by obernardovieira** [comment]
Sorry for the delay. Just tested. Still happening on 4.1.0
