### ISSUE TITLE
SignTypedData with Metamask

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/react-celo#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The signTypedData does not work when doing with metamask (but does on other wallets) 

### Steps to reproduce

call connection.signTypedData 

Get an error

### Expected behavior

get a signature

### Where is the problem happening?

Both

### Environment

n/a

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.1.0

### What wallet were you using?

metamask

### Additional context

I wonder if this is due to the lack of versioning (metamsk uses `signTypedData_v*`)?

**Comment by aaronmgdr** [comment]
confirmed that metamask extension will sign if  `_v3` or `_v4` is appending to the method name. AND the typed data is stringified. 

However once the version is appending wallet connect wallets (omni valora) no longer can sign.  🤔 

further more contractkit's CeloProvider (not the react CeloProvider, the ether one) treats the `eth_signTypedData` differently if this is a local account or not whereas with the versioning it will just always `forwardSend`  to the rpcCaller. 

still in investigation

**Comment by aaronmgdr** [comment]
similar issues https://github.com/snapshot-labs/snapshot/issues/950

**Comment by kamikazebr** [comment]
Yeah, i think you should use v3 and prepare to migrate to v4.

**Comment by aaronmgdr** [comment]
https://github.com/celo-org/celo-monorepo/blob/master/packages/sdk/connect/src/connection.ts#L277
