### ISSUE TITLE
Can't connect with Steak Wallet

### ISSUE THREAD

**Issue by calianlucian** [celo-org/react-celo#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to connect with Steak Wallet on Android, but the connection to the wallet app is not being established.

### Steps to reproduce

1. Go go react-celo.vercel.app
2. Select Mainnet network
3. Click Use Celo Now.
4. Select Steak Wallet from wallet list

The Steak Wallet application is opened, but no connection is established.

### Expected behavior

The page should connect to Steak Wallet displaying the account address and token balances.

### Where is the problem happening?

Mobile

### Environment

Device: Galaxy S7
OS: Android 8.0.0
Browser: Brave
Version: 1.44.101

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

4.1.0

### What wallet were you using?

Steak Wallet

### What is the dApp URL? (if applicable)

react-celo.vercel.app

**Comment by aaronmgdr** [comment]
steak wallet recently rebranded as OMNI. do you have latest version?

**Comment by calianlucian** [comment]
yes, version 3.0.5(119) of Omni

**Comment by aaronmgdr** [comment]
hmm I only have iPhone but its working for me. (i know the worst thing to hear) 

Any difference on https://react-celo-canary.vercel.app/ ?

**Comment by calianlucian** [comment]
Yes,  https://react-celo-canary.vercel.app is working fine. What would be the difference from react-celo.vercel.app?

**Comment by aaronmgdr** [comment]
-canary is master branch

react-celo is latest published package. 

good news though im publishing new package today

**Comment by calianlucian** [comment]
Great! Thanks for your quick replies.
