### ISSUE TITLE
Cannot do sendTransaction and signPersonal on iOS

### ISSUE THREAD

**Issue by miurelle** [celo-org/react-celo#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently having an issue on  `sendTransaction` and `signPersonal` workflow for iOS using https://react-celo.vercel.app/

We're sometimes receiving
1. Timeout
2. Stuck on the Modal
   -  ... is trying to perform actions...
   -  Switching to Valora ...

We've tested it on an Alfajores Network using an Alfajores app downloaded from Testflight

### Steps to reproduce

1. Connect Alfajores wallet to 'https://react-celo.vercel.app/', selecting the Alfajores option
2. Once connected, click on `Test SendTransaction`
3. Either the transaction timeouts or the modal is stuck.

### Expected behavior

Able to sendTransaction successfully.

### Screenshot

It stuck on this modal.

![image](https://user-images.githubusercontent.com/23333030/206614688-6ccdeca2-2fc2-4b37-a2e5-ec66dfbeaca9.png)

### Where is the problem happening?

Mobile

### Environment

iOS: 15.7.1 and 16.0.2

### What version of `react-celo` were you using? (This can be found in the list of wallets in the "Connect" modal)

v4.2.1

### What wallet were you using?

Alfajores

**Comment by aaronmgdr** [comment]
we are looking into this.

**Comment by 0xarthurxyz** [comment]
Deprioritising this issue based on feedback from CarbonPath (who opened issue): 

> We are in final testing phases now on alfajores. I discussed with my lead developer, and it turns out since we posted this issue our token purchase workflow has changed, so at the moment this doesn't affect us in our current state. Resolving this issue isn't our top priority now
