### ISSUE TITLE
Cannot connect using WalletConnect 

### ISSUE THREAD

**Issue by sprect8** [celo-org/react-celo#7]
When using WalletConnect and the test wallet (https://test.walletconnect.org/) I am unable to connect using the generated QR Code. The following error occurs:

`index.js:1200 Uncaught (in promise) Error: Invalid or missing bridge url parameter value
    at e.value (index.js:1200)
    at e.set (index.js:1559)
    at e.t (index.js:60)
    at new e (index.js:27)
    at e.<anonymous> (App.tsx:210)
    at tslib.es6.js:212
    at Object.next (tslib.es6.js:142)
    at tslib.es6.js:115
    at new Promise (<anonymous>)
    at l (tslib.es6.js:94)`

The generated QR Code is:
wc:143bb1ea9688892f39380560899ddfee7f1b0f35ae8304c0cfb35c3b1591b9bb@2?controller=false&publicKey=da77d4ec30304b65ccd031e142bdf3f2d465b7283643f92e58b7bf6a552d9b47&relay=%7B%22protocol%22%3A%22waku%22%7D

I tried to scan the generated URL in Trust Wallet and this also failed. 

Note this is currently running on my localhost machine.
Which WalletConnect-compatible wallet did you use for the wallet connect integration?

**Comment by medhakothari** [comment]
Apologies for the delay! Are you still seeing this error? It might have been that we were using wallet connect 2.0 which is still in beta

**Comment by kevinamado** [comment]
I' got the same issue. I Copy the deeplink :

wc:bdebc8b0ff3e0b78310e3dc382af729ab3f1d984497c572b4a800ec1e54737d8@2?relay-protocol=waku&symKey=ea043e7e58271714b8a029aacc87679cbee0170f7616229d0f70cb066d9aee32

and past it on the website https://test.walletconnect.org/

nothing append on the screen, but with the console one error show up :
![wc](https://user-images.githubusercontent.com/15381500/170744086-f46d1e43-2ce8-430a-ba7c-a5c86ccbc14e.png)
